# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py",
           "first.py"]

doc_url = "https://semmi88.github.io/nbdev_experimentation/"

git_url = "https://github.com/semmi88/nbdev_experimentation/tree/master/"

def custom_doc_links(name): return None
